certbot certonly --non-interactive --manual \
  --manual-auth-hook "./auth-hook.sh UPSERT yeshvantbhavnasi.info" \
  --manual-cleanup-hook "./auth-hook.sh DELETE yeshvantbhavnasi.info" \
  --preferred-challenge dns \
  --config-dir "./letsencrypt" \
  --work-dir "./letsencrypt" \
  --logs-dir "./letsencrypt" \
  --agree-tos \
  --manual-public-ip-logging-ok \
  --domains yeshvantbhavnasi.info,www.yeshvantbhavnasi.info \
  --email byeshvant@gmail.com